binary_value = ["Yes", "No"]
gender = ["Male", "Female", "Transgender"]
glob = [True, False]
diet = ["Vegetarian", "Vegan", "Pescatarian", "Omnivore", "Other"]
education = ["Bachelors", "Masters", "AtUni", "TradeSchool", "Phd", "HighSchool", "Diploma"]
exercise = ["Sedentary", "Light", "Moderate", "Active"]
pets = ["Dog", 'Cat', 'Bird', 'Fish', 'Reptile', 'None']
personality = ["Ambivert", "Extrovert", "Introvert"]
preferance = ["Male", "Female", "Transgender", "Everyone"]
relation_goal = ["LongTerm", "ShortTerm", "FiguringOut", "Friends"]
sleeping = ["EarlyBird", "NightOwl", "Balanced"]
smoke = ["Yes", "No", "Occasionally"]
star_sign = ["Aries", "Taurus", "Gemini", "Cancer", "Leo", "Virgo", "Libra", "Scorpio", "Sagittarius", "Capricorn", \
             "Aquarius", "Pisces"]
status = ["Single", "InARelationship", "Married", "Divorced", "Widowed"]
vaccinated = ["Yes", "No", "Partial", "PreferNotToSay"]
binary_boolean_value = [True, False]
